---
displayName: Zshrc
toolName: zshrc
author: ''
description: ''
tags: []
version: 1.0.0
repositoryUrl: https://github.com/zsh-users/zsh
relatedConfigs: ''
lastModified: '2025-07-21T09:10:44.639633Z'
---
# Path to your oh-my-zsh installation.
export ZSH="/home/user/.oh-my-zsh"

# Set name of the theme to load.
ZSH_THEME="robbyrussell"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# which plugins would you like to load?
plugins=(git)

source /oh-my-zsh.sh

# User configuration
export EDITOR='vim'
export VISUAL='vim'
