---
displayName: Bashrc
toolName: bashrc
author: ''
description: ''
tags: []
version: '0.0'
repositoryUrl: https://github.com/
relatedConfigs: ''
lastModified: '2025-07-21T09:10:44.606832Z'
---
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific aliases and functions
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# set PATH so it includes user's private bin if it exists
if [ -d "/home/jules/bin" ] ; then
    PATH="/home/jules/bin:/home/jules/.nvm/versions/node/v22.17.1/bin:/home/jules/.pyenv/shims:/home/jules/.pyenv/bin:/home/jules/.local/bin:/go/bin:/usr/local/go/bin:/usr/share/gradle/bin:/usr/share/maven/bin:/home/jules/.local/bin:/home/jules/.cargo/bin:/usr/local/bun/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
fi

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "tmux-256color" in
    xterm-color|*-256color) color_prompt=yes;;
esac
