" General settings
set nocompatible
filetype plugin indent on
syntax on
set encoding=utf-8

" Appearance
set number
set relativenumber
set cursorline
set scrolloff=8
set signcolumn=yes
colorscheme desert

" Searching
set incsearch
set hlsearch
set ignorecase
set smartcase

" Tabs and indentation
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent

" Key mappings
let mapleader = " "
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
